In [ ]:
# coffee data 2023

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

In [ ]:
df_2023 = pd.read_csv("arabica_clean_2023.csv")

In [ ]:
df_2023 = df_2023.drop(["ID", "Farm Name", "Lot Number", "Mill", "ICO Number", "Company", "Region", "Producer", "Number of Bags", "Bag Weight", "In-Country Partner", "Grading Date", "Owner", "Variety", "Status", "Color", "Expiration", "Certification Body", "Certification Address", "Certification Contact", "Quakers"], axis=1)
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Processing Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean Cup,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Category Two Defects
0,0,Colombia,1700-1930,2021 / 2022,Double Anaerobic Washed,8.58,8.50,8.42,8.58,8.25,8.42,10.0,10.0,10.0,8.58,0.0,89.33,11.8,0,3
1,1,Taiwan,1200,2021 / 2022,Washed / Wet,8.50,8.50,7.92,8.00,7.92,8.25,10.0,10.0,10.0,8.50,0.0,87.58,10.5,0,0
2,2,Laos,1300,2021 / 2022,Semi Washed,8.33,8.42,8.08,8.17,7.92,8.17,10.0,10.0,10.0,8.33,0.0,87.42,10.4,0,2
3,3,Costa Rica,1900,2022,Washed / Wet,8.08,8.17,8.17,8.25,8.17,8.08,10.0,10.0,10.0,8.25,0.0,87.17,11.8,0,0
4,4,Colombia,1850-2100,2022,"Honey,Mossto",8.33,8.33,8.08,8.25,7.92,7.92,10.0,10.0,10.0,8.25,0.0,87.08,11.6,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950,2022 / 2023,Natural / Dry,7.17,7.17,6.92,7.17,7.42,7.17,10.0,10.0,10.0,7.08,0.0,80.08,11.4,0,4
203,203,Nicaragua,1200,2022 / 2023,Natural / Dry,7.33,7.08,6.75,7.17,7.42,7.17,10.0,10.0,10.0,7.08,0.0,80.00,10.4,0,12
204,204,Laos,1300,2021 / 2022,Washed / Wet,7.25,7.17,7.08,7.00,7.08,7.08,10.0,10.0,10.0,7.00,0.0,79.67,11.6,0,11
205,205,El Salvador,1200,2023,Natural / Dry,6.50,6.75,6.75,7.17,7.08,7.00,10.0,10.0,10.0,6.83,0.0,78.08,11.0,0,13
206,206,Brazil,850-1100,2021 / 2022,SEMI-LAVADO,7.25,7.08,6.67,6.83,6.83,6.67,10.0,10.0,10.0,6.67,0.0,78.00,11.3,0,1

In [ ]:
df_2023["Moisture"] = df_2023["Moisture Percentage"]
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Processing Method,Aroma,Flavor,Aftertaste,Acidity,Body,...,Uniformity,Clean Cup,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Category Two Defects,Moisture
0,0,Colombia,1700-1930,2021 / 2022,Double Anaerobic Washed,8.58,8.50,8.42,8.58,8.25,...,10.0,10.0,10.0,8.58,0.0,89.33,11.8,0,3,11.8
1,1,Taiwan,1200,2021 / 2022,Washed / Wet,8.50,8.50,7.92,8.00,7.92,...,10.0,10.0,10.0,8.50,0.0,87.58,10.5,0,0,10.5
2,2,Laos,1300,2021 / 2022,Semi Washed,8.33,8.42,8.08,8.17,7.92,...,10.0,10.0,10.0,8.33,0.0,87.42,10.4,0,2,10.4
3,3,Costa Rica,1900,2022,Washed / Wet,8.08,8.17,8.17,8.25,8.17,...,10.0,10.0,10.0,8.25,0.0,87.17,11.8,0,0,11.8
4,4,Colombia,1850-2100,2022,"Honey,Mossto",8.33,8.33,8.08,8.25,7.92,...,10.0,10.0,10.0,8.25,0.0,87.08,11.6,0,2,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950,2022 / 2023,Natural / Dry,7.17,7.17,6.92,7.17,7.42,...,10.0,10.0,10.0,7.08,0.0,80.08,11.4,0,4,11.4
203,203,Nicaragua,1200,2022 / 2023,Natural / Dry,7.33,7.08,6.75,7.17,7.42,...,10.0,10.0,10.0,7.08,0.0,80.00,10.4,0,12,10.4
204,204,Laos,1300,2021 / 2022,Washed / Wet,7.25,7.17,7.08,7.00,7.08,...,10.0,10.0,10.0,7.00,0.0,79.67,11.6,0,11,11.6
205,205,El Salvador,1200,2023,Natural / Dry,6.50,6.75,6.75,7.17,7.08,...,10.0,10.0,10.0,6.83,0.0,78.08,11.0,0,13,11.0
206,206,Brazil,850-1100,2021 / 2022,SEMI-LAVADO,7.25,7.08,6.67,6.83,6.83,...,10.0,10.0,10.0,6.67,0.0,78.00,11.3,0,1,11.3

In [ ]:
df_2023["Moisture"] = df_2023["Moisture"].astype(float) / 100

In [ ]:
df_2023 = df_2023.drop(["Moisture Percentage",], axis=1)
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Processing Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean Cup,Sweetness,Overall,Defects,Total Cup Points,Category One Defects,Category Two Defects,Moisture
0,0,Colombia,1700-1930,2021 / 2022,Double Anaerobic Washed,8.58,8.50,8.42,8.58,8.25,8.42,10.0,10.0,10.0,8.58,0.0,89.33,0,3,0.118
1,1,Taiwan,1200,2021 / 2022,Washed / Wet,8.50,8.50,7.92,8.00,7.92,8.25,10.0,10.0,10.0,8.50,0.0,87.58,0,0,0.105
2,2,Laos,1300,2021 / 2022,Semi Washed,8.33,8.42,8.08,8.17,7.92,8.17,10.0,10.0,10.0,8.33,0.0,87.42,0,2,0.104
3,3,Costa Rica,1900,2022,Washed / Wet,8.08,8.17,8.17,8.25,8.17,8.08,10.0,10.0,10.0,8.25,0.0,87.17,0,0,0.118
4,4,Colombia,1850-2100,2022,"Honey,Mossto",8.33,8.33,8.08,8.25,7.92,7.92,10.0,10.0,10.0,8.25,0.0,87.08,0,2,0.116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950,2022 / 2023,Natural / Dry,7.17,7.17,6.92,7.17,7.42,7.17,10.0,10.0,10.0,7.08,0.0,80.08,0,4,0.114
203,203,Nicaragua,1200,2022 / 2023,Natural / Dry,7.33,7.08,6.75,7.17,7.42,7.17,10.0,10.0,10.0,7.08,0.0,80.00,0,12,0.104
204,204,Laos,1300,2021 / 2022,Washed / Wet,7.25,7.17,7.08,7.00,7.08,7.08,10.0,10.0,10.0,7.00,0.0,79.67,0,11,0.116
205,205,El Salvador,1200,2023,Natural / Dry,6.50,6.75,6.75,7.17,7.08,7.00,10.0,10.0,10.0,6.83,0.0,78.08,0,13,0.110
206,206,Brazil,850-1100,2021 / 2022,SEMI-LAVADO,7.25,7.08,6.67,6.83,6.83,6.67,10.0,10.0,10.0,6.67,0.0,78.00,0,1,0.113

In [ ]:
df_2023 = pd.get_dummies(df_2023, columns=["Processing Method"], prefix="Processing Method")

In [ ]:
# Convert boolean values (True/False) to integers (1/0)
processing_columns = [col for col in df_2023.columns if "Processing Method_" in col]
df_2023[processing_columns] = df_2023[processing_columns].astype(int)

In [ ]:
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,...,Processing Method_Anaerobico 1000h,Processing Method_Double Anaerobic Washed,Processing Method_Double Carbonic Maceration / Natural,"Processing Method_Honey,Mossto",Processing Method_Natural / Dry,Processing Method_Pulped natural / honey,Processing Method_SEMI-LAVADO,Processing Method_Semi Washed,Processing Method_Washed / Wet,Processing Method_Wet Hulling
0,0,Colombia,1700-1930,2021 / 2022,8.58,8.50,8.42,8.58,8.25,8.42,...,0,1,0,0,0,0,0,0,0,0
1,1,Taiwan,1200,2021 / 2022,8.50,8.50,7.92,8.00,7.92,8.25,...,0,0,0,0,0,0,0,0,1,0
2,2,Laos,1300,2021 / 2022,8.33,8.42,8.08,8.17,7.92,8.17,...,0,0,0,0,0,0,0,1,0,0
3,3,Costa Rica,1900,2022,8.08,8.17,8.17,8.25,8.17,8.08,...,0,0,0,0,0,0,0,0,1,0
4,4,Colombia,1850-2100,2022,8.33,8.33,8.08,8.25,7.92,7.92,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950,2022 / 2023,7.17,7.17,6.92,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
203,203,Nicaragua,1200,2022 / 2023,7.33,7.08,6.75,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
204,204,Laos,1300,2021 / 2022,7.25,7.17,7.08,7.00,7.08,7.08,...,0,0,0,0,0,0,0,0,1,0
205,205,El Salvador,1200,2023,6.50,6.75,6.75,7.17,7.08,7.00,...,0,0,0,0,1,0,0,0,0,0
206,206,Brazil,850-1100,2021 / 2022,7.25,7.08,6.67,6.83,6.83,6.67,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
def clean_altitude(altitude):
    if pd.isnull(altitude) or altitude == "." or str(altitude).lower() == "variety":
        return np.nan

    altitude = str(altitude).replace(",", "")

    if "-" in altitude:
        numbers = [float(x) for x in altitude.split("-") if x.replace(".", "", 1).isdigit()]
        return np.mean(numbers) if numbers else np.nan

    if altitude.replace(".", "", 1).isdigit():
        return float(altitude)

    return np.nan

# Apply cleaning function
df_2023.loc[:, "Altitude"] = df_2023["Altitude"].astype(str).apply(clean_altitude)

# Fill missing values with median altitude
df_2023.loc[:, "Altitude"] = df_2023["Altitude"].fillna(df_2023["Altitude"].median())

# Display cleaned Altitude column
print(df_2023["Altitude"])

0      1815.0
1      1200.0
2      1300.0
3      1900.0
4      1975.0
        ...
202     950.0
203    1200.0
204    1300.0
205    1200.0
206     975.0
Name: Altitude, Length: 207, dtype: object

<ipython-input-38-ed38c36d9c2a>:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_2023.loc[:, "Altitude"] = df_2023["Altitude"].fillna(df_2023["Altitude"].median())

In [ ]:
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,...,Processing Method_Anaerobico 1000h,Processing Method_Double Anaerobic Washed,Processing Method_Double Carbonic Maceration / Natural,"Processing Method_Honey,Mossto",Processing Method_Natural / Dry,Processing Method_Pulped natural / honey,Processing Method_SEMI-LAVADO,Processing Method_Semi Washed,Processing Method_Washed / Wet,Processing Method_Wet Hulling
0,0,Colombia,1815.0,2021 / 2022,8.58,8.50,8.42,8.58,8.25,8.42,...,0,1,0,0,0,0,0,0,0,0
1,1,Taiwan,1200.0,2021 / 2022,8.50,8.50,7.92,8.00,7.92,8.25,...,0,0,0,0,0,0,0,0,1,0
2,2,Laos,1300.0,2021 / 2022,8.33,8.42,8.08,8.17,7.92,8.17,...,0,0,0,0,0,0,0,1,0,0
3,3,Costa Rica,1900.0,2022,8.08,8.17,8.17,8.25,8.17,8.08,...,0,0,0,0,0,0,0,0,1,0
4,4,Colombia,1975.0,2022,8.33,8.33,8.08,8.25,7.92,7.92,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950.0,2022 / 2023,7.17,7.17,6.92,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
203,203,Nicaragua,1200.0,2022 / 2023,7.33,7.08,6.75,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
204,204,Laos,1300.0,2021 / 2022,7.25,7.17,7.08,7.00,7.08,7.08,...,0,0,0,0,0,0,0,0,1,0
205,205,El Salvador,1200.0,2023,6.50,6.75,6.75,7.17,7.08,7.00,...,0,0,0,0,1,0,0,0,0,0
206,206,Brazil,975.0,2021 / 2022,7.25,7.08,6.67,6.83,6.83,6.67,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
df_2023["Harvest Year"] = df_2023["Harvest Year"].replace("Unknown", "2023")

In [ ]:
def parse_harvest_year(year_str):
    """
    Convert a string like '2023' or '2023 / 2024' to a numeric value.
    For a range, we take the midpoint. E.g., '2023 / 2024' -> 2023.5
    """
    # Check if there's a slash, indicating a range
    if '/' in year_str:
        start_str, end_str = year_str.split('/')
        start_year = float(start_str.strip())
        end_year = float(end_str.strip())
        return (start_year + end_year) / 2.0
    else:
        # Single year, just parse as float
        return float(year_str.strip())

# Apply the function to the 'HarvestYear' column
df_2023['Harvest Year'] = df_2023['Harvest Year'].apply(parse_harvest_year)

In [ ]:
display(df_2023)

,Unnamed: 0,Country of Origin,Altitude,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,...,Processing Method_Anaerobico 1000h,Processing Method_Double Anaerobic Washed,Processing Method_Double Carbonic Maceration / Natural,"Processing Method_Honey,Mossto",Processing Method_Natural / Dry,Processing Method_Pulped natural / honey,Processing Method_SEMI-LAVADO,Processing Method_Semi Washed,Processing Method_Washed / Wet,Processing Method_Wet Hulling
0,0,Colombia,1815.0,2021.5,8.58,8.50,8.42,8.58,8.25,8.42,...,0,1,0,0,0,0,0,0,0,0
1,1,Taiwan,1200.0,2021.5,8.50,8.50,7.92,8.00,7.92,8.25,...,0,0,0,0,0,0,0,0,1,0
2,2,Laos,1300.0,2021.5,8.33,8.42,8.08,8.17,7.92,8.17,...,0,0,0,0,0,0,0,1,0,0
3,3,Costa Rica,1900.0,2022.0,8.08,8.17,8.17,8.25,8.17,8.08,...,0,0,0,0,0,0,0,0,1,0
4,4,Colombia,1975.0,2022.0,8.33,8.33,8.08,8.25,7.92,7.92,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,Brazil,950.0,2022.5,7.17,7.17,6.92,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
203,203,Nicaragua,1200.0,2022.5,7.33,7.08,6.75,7.17,7.42,7.17,...,0,0,0,0,1,0,0,0,0,0
204,204,Laos,1300.0,2021.5,7.25,7.17,7.08,7.00,7.08,7.08,...,0,0,0,0,0,0,0,0,1,0
205,205,El Salvador,1200.0,2023.0,6.50,6.75,6.75,7.17,7.08,7.00,...,0,0,0,0,1,0,0,0,0,0
206,206,Brazil,975.0,2021.5,7.25,7.08,6.67,6.83,6.83,6.67,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
df_2023 = df_2023.drop(["Unnamed: 0"], axis=1)
df_2023.to_csv("coffee_data_2023.csv", index=False)