In [ ]:
# arabica 2008

In [ ]:
import pandas as pd
from IPython.display import display
import re
import numpy as np

In [ ]:
df = pd.read_csv("arabica_2008.csv")

In [ ]:
display(df)

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.00,1800.00,1700.00
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.00,2200.00,2000.00
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,Arabica,juan carlos garcia lopez,Mexico,el centenario,NaN,"la esperanza, municipio juchique de ferrer, ve...",1104328663,terra mia,900,...,NaN,20,"September 17th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,900.00,900.00,900.00
1307,1308,Arabica,myriam kaplan-pasternak,Haiti,200 farms,NaN,coeb koperativ ekselsyo basen (350 members),NaN,haiti coffee,~350m,...,Blue-Green,16,"May 24th, 2013",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,350.00,350.00,350.00
1308,1309,Arabica,"exportadora atlantic, s.a.",Nicaragua,finca las marías,017-053-0211/ 017-053-0212,beneficio atlantic condega,017-053-0211/ 017-053-0212,exportadora atlantic s.a,1100,...,Green,5,"June 6th, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1100.00,1100.00,1100.00
1309,1310,Arabica,juan luis alvarado romero,Guatemala,finca el limon,NaN,beneficio serben,11/853/165,unicafe,4650,...,Green,4,"May 24th, 2013",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,ft,1417.32,1417.32,1417.32
1310,1312,Arabica,bismarck castro,Honduras,los hicaques,103,cigrah s.a de c.v.,13-111-053,cigrah s.a de c.v,1400,...,Green,2,"April 28th, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.00,1400.00,1400.00

In [ ]:
df = df.drop(["Species", "Farm.Name", "Lot.Number", "Mill", "ICO.Number", "Company", "Altitude", "Region", "Producer", "Number.of.Bags", "Bag.Weight", "In.Country.Partner", "Grading.Date", "Owner.1", "Variety", "Color", "Expiration", "Certification.Body", "Certification.Address", "Certification.Contact", "altitude_low_meters", "altitude_high_meters"], axis=1)

In [ ]:
display(df)

,Unnamed: 0,Owner,Country.of.Origin,Harvest.Year,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,...,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,unit_of_measurement,altitude_mean_meters
0,1,metad plc,Ethiopia,2014,Washed / Wet,8.67,8.83,8.67,8.75,8.50,...,10.00,10.00,8.75,90.58,0.12,0,0.0,0,m,2075.00
1,2,metad plc,Ethiopia,2014,Washed / Wet,8.75,8.67,8.50,8.58,8.42,...,10.00,10.00,8.58,89.92,0.12,0,0.0,1,m,2075.00
2,3,grounds for health admin,Guatemala,NaN,NaN,8.42,8.50,8.42,8.42,8.33,...,10.00,10.00,9.25,89.75,0.00,0,0.0,0,m,1700.00
3,4,yidnekachew dabessa,Ethiopia,2014,Natural / Dry,8.17,8.58,8.42,8.42,8.50,...,10.00,10.00,8.67,89.00,0.11,0,0.0,2,m,2000.00
4,5,metad plc,Ethiopia,2014,Washed / Wet,8.25,8.50,8.25,8.50,8.42,...,10.00,10.00,8.58,88.83,0.12,0,0.0,2,m,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,juan carlos garcia lopez,Mexico,2012,Washed / Wet,7.08,6.83,6.25,7.42,7.25,...,0.00,10.00,6.75,68.33,0.11,0,0.0,20,m,900.00
1307,1308,myriam kaplan-pasternak,Haiti,2012,Natural / Dry,6.75,6.58,6.42,6.67,7.08,...,6.00,6.00,6.42,67.92,0.14,8,0.0,16,m,350.00
1308,1309,"exportadora atlantic, s.a.",Nicaragua,2016,Other,7.25,6.58,6.33,6.25,6.42,...,6.00,6.00,6.17,63.08,0.13,1,0.0,5,m,1100.00
1309,1310,juan luis alvarado romero,Guatemala,2012,Washed / Wet,7.50,6.67,6.67,7.67,7.33,...,1.33,1.33,6.67,59.83,0.10,0,0.0,4,ft,1417.32
1310,1312,bismarck castro,Honduras,2017,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.12,0,0.0,2,m,1400.00

In [ ]:
df = df.dropna(subset=['altitude_mean_meters'])

In [ ]:
display(df)

,Unnamed: 0,Owner,Country.of.Origin,Harvest.Year,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,...,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,unit_of_measurement,altitude_mean_meters
0,1,metad plc,Ethiopia,2014,Washed / Wet,8.67,8.83,8.67,8.75,8.50,...,10.00,10.00,8.75,90.58,0.12,0,0.0,0,m,2075.00
1,2,metad plc,Ethiopia,2014,Washed / Wet,8.75,8.67,8.50,8.58,8.42,...,10.00,10.00,8.58,89.92,0.12,0,0.0,1,m,2075.00
2,3,grounds for health admin,Guatemala,NaN,NaN,8.42,8.50,8.42,8.42,8.33,...,10.00,10.00,9.25,89.75,0.00,0,0.0,0,m,1700.00
3,4,yidnekachew dabessa,Ethiopia,2014,Natural / Dry,8.17,8.58,8.42,8.42,8.50,...,10.00,10.00,8.67,89.00,0.11,0,0.0,2,m,2000.00
4,5,metad plc,Ethiopia,2014,Washed / Wet,8.25,8.50,8.25,8.50,8.42,...,10.00,10.00,8.58,88.83,0.12,0,0.0,2,m,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,juan carlos garcia lopez,Mexico,2012,Washed / Wet,7.08,6.83,6.25,7.42,7.25,...,0.00,10.00,6.75,68.33,0.11,0,0.0,20,m,900.00
1307,1308,myriam kaplan-pasternak,Haiti,2012,Natural / Dry,6.75,6.58,6.42,6.67,7.08,...,6.00,6.00,6.42,67.92,0.14,8,0.0,16,m,350.00
1308,1309,"exportadora atlantic, s.a.",Nicaragua,2016,Other,7.25,6.58,6.33,6.25,6.42,...,6.00,6.00,6.17,63.08,0.13,1,0.0,5,m,1100.00
1309,1310,juan luis alvarado romero,Guatemala,2012,Washed / Wet,7.50,6.67,6.67,7.67,7.33,...,1.33,1.33,6.67,59.83,0.10,0,0.0,4,ft,1417.32
1310,1312,bismarck castro,Honduras,2017,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.12,0,0.0,2,m,1400.00

In [ ]:
df['Altitude'] = df['altitude_mean_meters'].astype(float)

In [ ]:
df = df.drop(['altitude_mean_meters'], axis=1)

In [ ]:
display(df)

,Unnamed: 0,Owner,Country.of.Origin,Harvest.Year,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,...,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,unit_of_measurement,Altitude
0,1,metad plc,Ethiopia,2014,Washed / Wet,8.67,8.83,8.67,8.75,8.50,...,10.00,10.00,8.75,90.58,0.12,0,0.0,0,m,2075.00
1,2,metad plc,Ethiopia,2014,Washed / Wet,8.75,8.67,8.50,8.58,8.42,...,10.00,10.00,8.58,89.92,0.12,0,0.0,1,m,2075.00
2,3,grounds for health admin,Guatemala,NaN,NaN,8.42,8.50,8.42,8.42,8.33,...,10.00,10.00,9.25,89.75,0.00,0,0.0,0,m,1700.00
3,4,yidnekachew dabessa,Ethiopia,2014,Natural / Dry,8.17,8.58,8.42,8.42,8.50,...,10.00,10.00,8.67,89.00,0.11,0,0.0,2,m,2000.00
4,5,metad plc,Ethiopia,2014,Washed / Wet,8.25,8.50,8.25,8.50,8.42,...,10.00,10.00,8.58,88.83,0.12,0,0.0,2,m,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,juan carlos garcia lopez,Mexico,2012,Washed / Wet,7.08,6.83,6.25,7.42,7.25,...,0.00,10.00,6.75,68.33,0.11,0,0.0,20,m,900.00
1307,1308,myriam kaplan-pasternak,Haiti,2012,Natural / Dry,6.75,6.58,6.42,6.67,7.08,...,6.00,6.00,6.42,67.92,0.14,8,0.0,16,m,350.00
1308,1309,"exportadora atlantic, s.a.",Nicaragua,2016,Other,7.25,6.58,6.33,6.25,6.42,...,6.00,6.00,6.17,63.08,0.13,1,0.0,5,m,1100.00
1309,1310,juan luis alvarado romero,Guatemala,2012,Washed / Wet,7.50,6.67,6.67,7.67,7.33,...,1.33,1.33,6.67,59.83,0.10,0,0.0,4,ft,1417.32
1310,1312,bismarck castro,Honduras,2017,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.12,0,0.0,2,m,1400.00

In [ ]:
df = df.drop(['Unnamed: 0', 'Owner'], axis=1)

In [ ]:
display(df)

,Country.of.Origin,Harvest.Year,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,unit_of_measurement,Altitude
0,Ethiopia,2014,Washed / Wet,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,10.00,8.75,90.58,0.12,0,0.0,0,m,2075.00
1,Ethiopia,2014,Washed / Wet,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,10.00,8.58,89.92,0.12,0,0.0,1,m,2075.00
2,Guatemala,NaN,NaN,8.42,8.50,8.42,8.42,8.33,8.42,10.00,10.00,10.00,9.25,89.75,0.00,0,0.0,0,m,1700.00
3,Ethiopia,2014,Natural / Dry,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,10.00,8.67,89.00,0.11,0,0.0,2,m,2000.00
4,Ethiopia,2014,Washed / Wet,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,10.00,8.58,88.83,0.12,0,0.0,2,m,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,Mexico,2012,Washed / Wet,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,10.00,6.75,68.33,0.11,0,0.0,20,m,900.00
1307,Haiti,2012,Natural / Dry,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,6.00,6.42,67.92,0.14,8,0.0,16,m,350.00
1308,Nicaragua,2016,Other,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,6.00,6.17,63.08,0.13,1,0.0,5,m,1100.00
1309,Guatemala,2012,Washed / Wet,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,1.33,6.67,59.83,0.10,0,0.0,4,ft,1417.32
1310,Honduras,2017,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0,0.0,2,m,1400.00

In [ ]:
df = df.drop(["unit_of_measurement"], axis=1)

In [ ]:
display(df)

,Country.of.Origin,Harvest.Year,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,Altitude
0,Ethiopia,2014,Washed / Wet,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,10.00,8.75,90.58,0.12,0,0.0,0,2075.00
1,Ethiopia,2014,Washed / Wet,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,10.00,8.58,89.92,0.12,0,0.0,1,2075.00
2,Guatemala,NaN,NaN,8.42,8.50,8.42,8.42,8.33,8.42,10.00,10.00,10.00,9.25,89.75,0.00,0,0.0,0,1700.00
3,Ethiopia,2014,Natural / Dry,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,10.00,8.67,89.00,0.11,0,0.0,2,2000.00
4,Ethiopia,2014,Washed / Wet,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,10.00,8.58,88.83,0.12,0,0.0,2,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,Mexico,2012,Washed / Wet,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,10.00,6.75,68.33,0.11,0,0.0,20,900.00
1307,Haiti,2012,Natural / Dry,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,6.00,6.42,67.92,0.14,8,0.0,16,350.00
1308,Nicaragua,2016,Other,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,6.00,6.17,63.08,0.13,1,0.0,5,1100.00
1309,Guatemala,2012,Washed / Wet,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,1.33,6.67,59.83,0.10,0,0.0,4,1417.32
1310,Honduras,2017,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0,0.0,2,1400.00

In [ ]:
df = pd.get_dummies(df, columns=["Processing.Method"], prefix="Processing Method")

In [ ]:
# Convert boolean values (True/False) to integers (1/0)
processing_columns = [col for col in df.columns if "Processing Method_" in col]
df[processing_columns] = df[processing_columns].astype(int)

In [ ]:
display(df)

,Country.of.Origin,Harvest.Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,...,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,Altitude,Processing Method_Natural / Dry,Processing Method_Other,Processing Method_Pulped natural / honey,Processing Method_Semi-washed / Semi-pulped,Processing Method_Washed / Wet
0,Ethiopia,2014,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,...,0.12,0,0.0,0,2075.00,0,0,0,0,1
1,Ethiopia,2014,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,...,0.12,0,0.0,1,2075.00,0,0,0,0,1
2,Guatemala,NaN,8.42,8.50,8.42,8.42,8.33,8.42,10.00,10.00,...,0.00,0,0.0,0,1700.00,0,0,0,0,0
3,Ethiopia,2014,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,...,0.11,0,0.0,2,2000.00,1,0,0,0,0
4,Ethiopia,2014,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,...,0.12,0,0.0,2,2075.00,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,Mexico,2012,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,...,0.11,0,0.0,20,900.00,0,0,0,0,1
1307,Haiti,2012,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,...,0.14,8,0.0,16,350.00,1,0,0,0,0
1308,Nicaragua,2016,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,...,0.13,1,0.0,5,1100.00,0,1,0,0,0
1309,Guatemala,2012,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,...,0.10,0,0.0,4,1417.32,0,0,0,0,1
1310,Honduras,2017,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.12,0,0.0,2,1400.00,0,0,0,0,0

In [ ]:
print(df["Harvest.Year"].unique())

['2014' nan 'March 2010' 'Sept 2009 - April 2010' 'May-August' '2015'
 '2012' '2011' '2013' '2016' '2015/2016' '2010' '2009/2010' 'Fall 2009'
 '2017' '2009 / 2010' '2010-2011' '2009 - 2010' '2013/2014' '2017 / 2018'
 'December 2009-March 2010' '2014/2015' '2011/2012' 'January 2011' '4T/10'
 '23 July 2010' 'January Through April' '1T/2011' '4t/2010' '4T/2010'
 'August to December' 'Mayo a Julio' '47/2010' 'Abril - Julio' '4t/2011'
 'Abril - Julio /2011' 'Spring 2011 in Colombia.' '2016 / 2017' '3T/2011'
 '1t/2011' '2018' '4T72010' '08/09 crop']

In [ ]:
def extract_year(value):
    if pd.isna(value):
        return np.nan

    # Find all years in the string
    years = re.findall(r'\d{4}', str(value))

    if len(years) == 1:
        return float(years[0])

    elif len(years) > 1:
        return float(sum(map(int, years)) / len(years))

    return np.nan

# Apply the function to the column
df["Harvest.Year"] = df["Harvest.Year"].apply(extract_year)

# Display the unique transformed values
print(df["Harvest.Year"].unique())

[2014.     nan 2010.  2009.5 2015.  2012.  2011.  2013.  2016.  2015.5
 2009.  2017.  2010.5 2013.5 2017.5 2014.5 2011.5 2016.5 2018.  7201. ]

In [ ]:
print(df["Harvest.Year"].unique())

[2014.     nan 2010.  2009.5 2015.  2012.  2011.  2013.  2016.  2015.5
 2009.  2017.  2010.5 2013.5 2017.5 2014.5 2011.5 2016.5 2018.  7201. ]

In [ ]:
nan_count = df["Harvest.Year"].isna().sum()
print(f"Number of NaN values in Harvest.Year: {nan_count}")

Number of NaN values in Harvest.Year: 26

In [ ]:
df = df.dropna(subset=['Harvest.Year'])

In [ ]:
df["Harvest Year"] = df["Harvest.Year"]

KeyError: 'Harvest.Year'

In [ ]:
df.to_csv("coffee_data_2008.csv", index=False)

In [ ]:
display(df)

,Country.of.Origin,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,...,Category.One.Defects,Quakers,Category.Two.Defects,Altitude,Processing Method_Natural / Dry,Processing Method_Other,Processing Method_Pulped natural / honey,Processing Method_Semi-washed / Semi-pulped,Processing Method_Washed / Wet,Harvest Year
0,Ethiopia,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,10.00,...,0,0.0,0,2075.00,0,0,0,0,1,2014.0
1,Ethiopia,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,10.00,...,0,0.0,1,2075.00,0,0,0,0,1,2014.0
3,Ethiopia,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,10.00,...,0,0.0,2,2000.00,1,0,0,0,0,2014.0
4,Ethiopia,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,10.00,...,0,0.0,2,2075.00,0,0,0,0,1,2014.0
7,Ethiopia,8.25,8.33,8.50,8.42,8.33,8.50,10.00,10.00,9.33,...,0,0.0,0,1635.00,0,0,0,0,0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,Mexico,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,10.00,...,0,0.0,20,900.00,0,0,0,0,1,2012.0
1307,Haiti,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,6.00,...,8,0.0,16,350.00,1,0,0,0,0,2012.0
1308,Nicaragua,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,6.00,...,1,0.0,5,1100.00,0,1,0,0,0,2016.0
1309,Guatemala,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,1.33,...,0,0.0,4,1417.32,0,0,0,0,1,2012.0
1310,Honduras,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0,0.0,2,1400.00,0,0,0,0,0,2017.0