In [ ]:
# arabica 2024-25

In [ ]:
import pandas as pd
from IPython.display import display

In [ ]:
df_2024 = pd.read_csv("arabica-2024-25.csv")

In [ ]:
df_2024 = df_2024.drop(["0", "2", "Number of Bags", "Farm Name", "Bag Weight", "Lot Number", "In-Country Partner", "Mill", "ICO Number", "Company", "Owner", "Variety", "Region", "Producer", "Defects", "Color", "Quakers", "Expiration", "Certification Body", "Certification Address", "Status", "Certification Contact", "Grading Date"], axis=1)

In [ ]:
display(df_2024)

,Country of Origin,Harvest Year,Altitude,Processing Method,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,Overall,Body,Balance,Total Cup Points,Moisture,Category One Defects,Category Two Defects,Cupper Points
0,Thailand,2023 / 2024,1403,Natural / Dry,8.50,10.0,8.42,10.0,8.50,10.0,8.33,8.50,8.17,8.33,88.75,10 %,0 full defects,1 full defects,8.50
1,Thailand,2023 / 2024,1350,Pulped natural / honey,8.58,10.0,8.50,10.0,8.33,10.0,8.42,8.50,8.17,8.25,88.75,9.3 %,0 full defects,1 full defects,8.50
2,Brazil,2023,1100,Natural Fermentation / Sundried,8.50,10.0,8.50,10.0,8.25,10.0,8.42,8.42,8.25,8.17,88.50,10.8 %,0 full defects,2 full defects,8.42
3,Thailand,2019 / 2020,1443,Washed / Wet,8.67,10.0,8.50,10.0,8.33,10.0,8.00,8.42,8.08,8.33,88.33,11.2 %,0 full defects,0 full defects,8.42
4,Thailand,2023 / 2024,1445,Washed / Wet,8.42,10.0,8.58,10.0,8.33,10.0,8.17,8.50,8.08,8.17,88.25,9.9 %,0 full defects,1 full defects,8.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,2023 / 2024,670,Natural / Dry,7.92,10.0,7.83,10.0,7.75,10.0,7.75,7.83,7.92,7.75,84.75,11 %,0 full defects,3 full defects,7.83
145,Thailand,2023 / 2024,1100 - 1200,Pulped natural / honey,7.67,10.0,7.75,10.0,7.58,10.0,7.92,7.83,7.83,7.67,84.25,10.3 %,0 full defects,0 full defects,7.83
146,Thailand,2023 / 2024,1100,Washed / Wet,7.83,10.0,7.92,10.0,7.75,10.0,7.75,7.67,7.92,7.83,84.67,10.7 %,0 full defects,0 full defects,7.67
147,Thailand,2023 / 2024,1400,Washed / Wet,7.67,10.0,7.92,10.0,7.75,10.0,7.67,8.00,7.92,7.75,84.67,10.3 %,0 full defects,3 full defects,8.00
148,Ethiopia,2023,2000,Washed / Wet,7.83,10.0,7.92,10.0,7.83,10.0,7.83,7.83,7.67,7.75,84.67,10.5 %,0 full defects,1 full defects,7.83

In [ ]:
df_2024["Moisture"] = df_2024["Moisture"].str.replace("%", "").astype(float) / 100

In [ ]:
display(df_2024)

,Country of Origin,Harvest Year,Altitude,Processing Method,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,Overall,Body,Balance,Total Cup Points,Moisture,Category One Defects,Category Two Defects,Cupper Points
0,Thailand,2023 / 2024,1403,Natural / Dry,8.50,10.0,8.42,10.0,8.50,10.0,8.33,8.50,8.17,8.33,88.75,0.100,0 full defects,1 full defects,8.50
1,Thailand,2023 / 2024,1350,Pulped natural / honey,8.58,10.0,8.50,10.0,8.33,10.0,8.42,8.50,8.17,8.25,88.75,0.093,0 full defects,1 full defects,8.50
2,Brazil,2023,1100,Natural Fermentation / Sundried,8.50,10.0,8.50,10.0,8.25,10.0,8.42,8.42,8.25,8.17,88.50,0.108,0 full defects,2 full defects,8.42
3,Thailand,2019 / 2020,1443,Washed / Wet,8.67,10.0,8.50,10.0,8.33,10.0,8.00,8.42,8.08,8.33,88.33,0.112,0 full defects,0 full defects,8.42
4,Thailand,2023 / 2024,1445,Washed / Wet,8.42,10.0,8.58,10.0,8.33,10.0,8.17,8.50,8.08,8.17,88.25,0.099,0 full defects,1 full defects,8.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,2023 / 2024,670,Natural / Dry,7.92,10.0,7.83,10.0,7.75,10.0,7.75,7.83,7.92,7.75,84.75,0.110,0 full defects,3 full defects,7.83
145,Thailand,2023 / 2024,1100 - 1200,Pulped natural / honey,7.67,10.0,7.75,10.0,7.58,10.0,7.92,7.83,7.83,7.67,84.25,0.103,0 full defects,0 full defects,7.83
146,Thailand,2023 / 2024,1100,Washed / Wet,7.83,10.0,7.92,10.0,7.75,10.0,7.75,7.67,7.92,7.83,84.67,0.107,0 full defects,0 full defects,7.67
147,Thailand,2023 / 2024,1400,Washed / Wet,7.67,10.0,7.92,10.0,7.75,10.0,7.67,8.00,7.92,7.75,84.67,0.103,0 full defects,3 full defects,8.00
148,Ethiopia,2023,2000,Washed / Wet,7.83,10.0,7.92,10.0,7.83,10.0,7.83,7.83,7.67,7.75,84.67,0.105,0 full defects,1 full defects,7.83

In [ ]:
df_2024 = pd.get_dummies(df_2024, columns=["Processing Method"], prefix="Processing Method")

In [ ]:
# Convert boolean values (True/False) to integers (1/0)
processing_columns = [col for col in df_2024.columns if "Processing Method_" in col]
df_2024[processing_columns] = df_2024[processing_columns].astype(int)

In [ ]:
display(df_2024)

,Country of Origin,Harvest Year,Altitude,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,...,Processing Method_Dry Carbonic,Processing Method_Dynamic Cherry,Processing Method_Fermented in barrels with figs 4days,Processing Method_Natural / Dry,Processing Method_Natural Fermentation / Sundried,Processing Method_Pulped natural / honey,Processing Method_WASHED,Processing Method_Wash Carbonic Process,Processing Method_Washed / Wet,Processing Method_intrinsic cherry
0,Thailand,2023 / 2024,1403,8.50,10.0,8.42,10.0,8.50,10.0,8.33,...,0,0,0,1,0,0,0,0,0,0
1,Thailand,2023 / 2024,1350,8.58,10.0,8.50,10.0,8.33,10.0,8.42,...,0,0,0,0,0,1,0,0,0,0
2,Brazil,2023,1100,8.50,10.0,8.50,10.0,8.25,10.0,8.42,...,0,0,0,0,1,0,0,0,0,0
3,Thailand,2019 / 2020,1443,8.67,10.0,8.50,10.0,8.33,10.0,8.00,...,0,0,0,0,0,0,0,0,1,0
4,Thailand,2023 / 2024,1445,8.42,10.0,8.58,10.0,8.33,10.0,8.17,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,2023 / 2024,670,7.92,10.0,7.83,10.0,7.75,10.0,7.75,...,0,0,0,1,0,0,0,0,0,0
145,Thailand,2023 / 2024,1100 - 1200,7.67,10.0,7.75,10.0,7.58,10.0,7.92,...,0,0,0,0,0,1,0,0,0,0
146,Thailand,2023 / 2024,1100,7.83,10.0,7.92,10.0,7.75,10.0,7.75,...,0,0,0,0,0,0,0,0,1,0
147,Thailand,2023 / 2024,1400,7.67,10.0,7.92,10.0,7.75,10.0,7.67,...,0,0,0,0,0,0,0,0,1,0
148,Ethiopia,2023,2000,7.83,10.0,7.92,10.0,7.83,10.0,7.83,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
# print(df_2024["Harvest Year"].unique())
print(df_2024["Altitude"].unique())

['1403' '1350' '1100' '1443' '1445' '1200-1580' '1900' '1550' '1200'
 '1300-1500' '1250' '1270' '1500' '2380' '2070' '1050' '1300' '1624'
 '1400' '1,200-1,300' '650' '1600-1800' '1728-1877' '1000' '1400-2200'
 '1980' '1450' '750' '300-600' '820' '1200-1400' '130-150' '1973' '1800'
 '1200 - 1500' '1600' '1400-1600' '1320' '1800-2100' '700' '1020'
 '200-400' '2500 above' '1100-1500' '.' '1798' '600' '800-1200'
 '1400 - 1900' 'Variety' '1252' '1000 - 1400' '180' '1480' '700-800' '900'
 '1600 - 1800' '230' '1700' '1650' '950' '670' '1100 - 1200' '2000']

In [ ]:
import numpy as np

def clean_altitude(altitude):
    if pd.isnull(altitude) or altitude == "." or str(altitude).lower() == "variety":
        return np.nan

    altitude = str(altitude).replace(",", "")

    if "-" in altitude:
        numbers = [float(x) for x in altitude.split("-") if x.replace(".", "", 1).isdigit()]
        return np.mean(numbers) if numbers else np.nan

    if altitude.replace(".", "", 1).isdigit():
        return float(altitude)

    return np.nan

# Apply cleaning function
df_2024.loc[:, "Altitude"] = df_2024["Altitude"].astype(str).apply(clean_altitude)

# Fill missing values with median altitude
df_2024.loc[:, "Altitude"] = df_2024["Altitude"].fillna(df_2024["Altitude"].median())

# Display cleaned Altitude column
print(df_2024["Altitude"])

0      1403.0
1      1350.0
2      1100.0
3      1443.0
4      1445.0
        ...
144     670.0
145    1320.0
146    1100.0
147    1400.0
148    2000.0
Name: Altitude, Length: 149, dtype: object

<ipython-input-78-22e6c69284dd>:22: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_2024.loc[:, "Altitude"] = df_2024["Altitude"].fillna(df_2024["Altitude"].median())

In [ ]:
df_2024["Harvest Year"] = df_2024["Harvest Year"].replace("Unknown", "2025")

In [ ]:
# df_2024 = pd.get_dummies(df_2024, columns=["Harvest Year"], prefix="Harvest Year")

In [ ]:
# harvest_columns = [col for col in df_2024.columns if "Harvest Year_" in col]
# df_2024[harvest_columns] = df_2024[harvest_columns].astype(int)

In [ ]:
# display(df_2024[harvest_columns])

KeyError: "None of [Index(['Harvest Year_2019 / 2020', 'Harvest Year_2022 / 2023',\n       'Harvest Year_2023', 'Harvest Year_2023 / 2024', 'Harvest Year_2024',\n       'Harvest Year_2024 / 2025', 'Harvest Year_2025'],\n      dtype='object')] are in the [columns]"

In [ ]:
df_2024["Moisture"] = df_2024["Moisture"].round(2)

In [ ]:
df_2024.to_csv("coffee_data.csv", index=False)

In [ ]:
print(df_2024["Harvest Year"].unique())

['2023 / 2024' '2023' '2019 / 2020' '2024' '2024 / 2025' '2025'
 '2022 / 2023']

In [ ]:
print(df_2024["Moisture"])

0      0.10
1      0.09
2      0.11
3      0.11
4      0.10
       ...
144    0.11
145    0.10
146    0.11
147    0.10
148    0.10
Name: Moisture, Length: 149, dtype: float64

In [ ]:
print(df_2024.isnull().sum())

Country of Origin                                         0
Altitude                                                  0
Aroma                                                     0
Uniformity                                                0
Flavor                                                    0
Clean Cup                                                 0
Aftertaste                                                0
Sweetness                                                 0
Acidity                                                   0
Overall                                                   0
Body                                                      0
Balance                                                   0
Total Cup Points                                          0
Moisture                                                  0
Category One Defects                                      0
Category Two Defects                                      0
Cupper Points                                             0
Processing Method_Aerobic natural                         0
Processing Method_Anaerobic Honey                         0
Processing Method_Dry Carbonic                            0
Processing Method_Dynamic Cherry                          0
Processing Method_Fermented in barrels with figs 4days    0
Processing Method_Natural / Dry                           0
Processing Method_Natural Fermentation / Sundried         0
Processing Method_Pulped natural / honey                  0
Processing Method_WASHED                                  0
Processing Method_Wash Carbonic Process                   0
Processing Method_Washed / Wet                            0
Processing Method_intrinsic cherry                        0
Harvest Year_2019 / 2020                                  0
Harvest Year_2022 / 2023                                  0
Harvest Year_2023                                         0
Harvest Year_2023 / 2024                                  0
Harvest Year_2024                                         0
Harvest Year_2024 / 2025                                  0
Harvest Year_2025                                         0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_columns = ["Altitude", "Aroma", "Flavor", "Acidity", "Sweetness", "Total Cup Points"]

df_2024[scaled_columns] = scaler.fit_transform(df_2024[scaled_columns])

In [ ]:
display(df_2024)

,Country of Origin,Altitude,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,Overall,...,Processing Method_Wash Carbonic Process,Processing Method_Washed / Wet,Processing Method_intrinsic cherry,Harvest Year_2019 / 2020,Harvest Year_2022 / 2023,Harvest Year_2023,Harvest Year_2023 / 2024,Harvest Year_2024,Harvest Year_2024 / 2025,Harvest Year_2025
0,Thailand,0.563839,0.844037,10.0,0.824176,10.0,8.50,0.0,0.880000,8.50,...,0,0,0,0,0,0,1,0,0,0
1,Thailand,0.540179,0.917431,10.0,0.912088,10.0,8.33,0.0,1.000000,8.50,...,0,0,0,0,0,0,1,0,0,0
2,Brazil,0.428571,0.844037,10.0,0.912088,10.0,8.25,0.0,1.000000,8.42,...,0,0,0,0,0,1,0,0,0,0
3,Thailand,0.581696,1.000000,10.0,0.912088,10.0,8.33,0.0,0.440000,8.42,...,0,1,0,1,0,0,0,0,0,0
4,Thailand,0.582589,0.770642,10.0,1.000000,10.0,8.33,0.0,0.666667,8.50,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,0.236607,0.311927,10.0,0.175824,10.0,7.75,0.0,0.106667,7.83,...,0,0,0,0,0,0,1,0,0,0
145,Thailand,0.526786,0.082569,10.0,0.087912,10.0,7.58,0.0,0.333333,7.83,...,0,0,0,0,0,0,1,0,0,0
146,Thailand,0.428571,0.229358,10.0,0.274725,10.0,7.75,0.0,0.106667,7.67,...,0,1,0,0,0,0,1,0,0,0
147,Thailand,0.562500,0.082569,10.0,0.274725,10.0,7.75,0.0,0.000000,8.00,...,0,1,0,0,0,0,1,0,0,0
148,Ethiopia,0.830357,0.229358,10.0,0.274725,10.0,7.83,0.0,0.213333,7.83,...,0,1,0,0,0,1,0,0,0,0

In [ ]:
df_2024 = df_2024.sort_values(by=["Harvest Year_2023", "Harvest Year_2024", "Harvest Year_2025"])

# Creating lag features (previous year's data for prediction)
df_2024["Previous Aroma"] = df_2024["Aroma"].shift(1)
df_2024["Previous Flavor"] = df_2024["Flavor"].shift(1)
df_2024["Previous Acidity"] = df_2024["Acidity"].shift(1)

# Drop first row since it will have NaN values due to shifting
df_2024 = df_2024.dropna()

In [ ]:
display(df_2024)

,Country of Origin,Altitude,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,Overall,...,Harvest Year_2019 / 2020,Harvest Year_2022 / 2023,Harvest Year_2023,Harvest Year_2023 / 2024,Harvest Year_2024,Harvest Year_2024 / 2025,Harvest Year_2025,Previous Aroma,Previous Flavor,Previous Acidity
1,Thailand,0.540179,0.917431,10.0,0.912088,10.0,8.33,0.0,1.000000,8.50,...,0,0,0,1,0,0,0,0.844037,0.824176,0.880000
3,Thailand,0.581696,1.000000,10.0,0.912088,10.0,8.33,0.0,0.440000,8.42,...,1,0,0,0,0,0,0,0.917431,0.912088,1.000000
4,Thailand,0.582589,0.770642,10.0,1.000000,10.0,8.33,0.0,0.666667,8.50,...,0,0,0,1,0,0,0,1.000000,0.912088,0.440000
5,Thailand,0.582589,0.688073,10.0,0.824176,10.0,8.33,0.0,0.773333,8.42,...,0,0,0,1,0,0,0,0.770642,1.000000,0.666667
6,Thailand,0.558036,1.000000,10.0,0.725275,10.0,8.17,0.0,0.666667,8.33,...,0,0,0,1,0,0,0,0.688073,0.824176,0.773333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Panama,0.517857,0.385321,10.0,0.450549,10.0,7.83,0.0,0.546667,8.17,...,0,0,1,0,0,0,0,0.385321,0.549451,0.333333
93,Taiwan,0.383929,0.155963,10.0,0.362637,10.0,7.92,0.0,0.440000,8.08,...,0,0,1,0,0,0,0,0.385321,0.450549,0.546667
94,Thailand,0.584821,0.385321,10.0,0.362637,10.0,7.83,0.0,0.546667,7.83,...,0,0,1,0,0,0,0,0.155963,0.362637,0.440000
98,Thailand,0.584821,0.311927,10.0,0.362637,10.0,7.83,0.0,0.440000,8.00,...,0,0,1,0,0,0,0,0.385321,0.362637,0.546667
148,Ethiopia,0.830357,0.229358,10.0,0.274725,10.0,7.83,0.0,0.213333,7.83,...,0,0,1,0,0,0,0,0.311927,0.362637,0.440000

In [ ]:
def parse_harvest_year(year_str):
    """
    Convert a string like '2023' or '2023 / 2024' to a numeric value.
    For a range, we take the midpoint. E.g., '2023 / 2024' -> 2023.5
    """
    # Check if there's a slash, indicating a range
    if '/' in year_str:
        start_str, end_str = year_str.split('/')
        start_year = float(start_str.strip())
        end_year = float(end_str.strip())
        return (start_year + end_year) / 2.0
    else:
        # Single year, just parse as float
        return float(year_str.strip())

# Apply the function to the 'HarvestYear' column
df_2024['Harvest Year'] = df_2024['Harvest Year'].apply(parse_harvest_year)

In [ ]:
df_2024['Category One Defects'] = df_2024['Category One Defects'].apply(lambda x: int(x.split()[0]))
df_2024['Category Two Defects'] = df_2024['Category Two Defects'].apply(lambda x: int(x.split()[0]))

In [ ]:
display(df_2024)
df_2024.to_csv("coffee_data_done_year.csv", index=False)

,Country of Origin,Harvest Year,Altitude,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,...,Processing Method_Dry Carbonic,Processing Method_Dynamic Cherry,Processing Method_Fermented in barrels with figs 4days,Processing Method_Natural / Dry,Processing Method_Natural Fermentation / Sundried,Processing Method_Pulped natural / honey,Processing Method_WASHED,Processing Method_Wash Carbonic Process,Processing Method_Washed / Wet,Processing Method_intrinsic cherry
0,Thailand,2023.5,1403.0,8.50,10.0,8.42,10.0,8.50,10.0,8.33,...,0,0,0,1,0,0,0,0,0,0
1,Thailand,2023.5,1350.0,8.58,10.0,8.50,10.0,8.33,10.0,8.42,...,0,0,0,0,0,1,0,0,0,0
2,Brazil,2023.0,1100.0,8.50,10.0,8.50,10.0,8.25,10.0,8.42,...,0,0,0,0,1,0,0,0,0,0
3,Thailand,2019.5,1443.0,8.67,10.0,8.50,10.0,8.33,10.0,8.00,...,0,0,0,0,0,0,0,0,1,0
4,Thailand,2023.5,1445.0,8.42,10.0,8.58,10.0,8.33,10.0,8.17,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,2023.5,670.0,7.92,10.0,7.83,10.0,7.75,10.0,7.75,...,0,0,0,1,0,0,0,0,0,0
145,Thailand,2023.5,1320.0,7.67,10.0,7.75,10.0,7.58,10.0,7.92,...,0,0,0,0,0,1,0,0,0,0
146,Thailand,2023.5,1100.0,7.83,10.0,7.92,10.0,7.75,10.0,7.75,...,0,0,0,0,0,0,0,0,1,0
147,Thailand,2023.5,1400.0,7.67,10.0,7.92,10.0,7.75,10.0,7.67,...,0,0,0,0,0,0,0,0,1,0
148,Ethiopia,2023.0,2000.0,7.83,10.0,7.92,10.0,7.83,10.0,7.83,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
features_0_10 = [
    'Aroma', 'Uniformity', 'Flavor', 'Clean Cup',
    'Aftertaste', 'Sweetness', 'Acidity', 'Overall',
    'Body', 'Balance'
]
target_1_100 = ['Total Cup Points']
scaler_features = MinMaxScaler(feature_range=(0, 1))
df_2024[features_0_10] = scaler_features.fit_transform(df_2024[features_0_10])
scaler_target = MinMaxScaler(feature_range=(0, 1))
df_2024[target_1_100] = scaler_target.fit_transform(df_2024[target_1_100])
display(df_2024)

,Country of Origin,Harvest Year,Altitude,Aroma,Uniformity,Flavor,Clean Cup,Aftertaste,Sweetness,Acidity,...,Processing Method_Dynamic Cherry,Processing Method_Fermented in barrels with figs 4days,Processing Method_Natural / Dry,Processing Method_Natural Fermentation / Sundried,Processing Method_Pulped natural / honey,Processing Method_WASHED,Processing Method_Wash Carbonic Process,Processing Method_Washed / Wet,Processing Method_intrinsic cherry,HarvestYear_numeric
0,Thailand,2023.5,1403.0,0.844037,0.0,0.824176,0.0,1.000000,0.0,0.880000,...,0,0,1,0,0,0,0,0,0,2023.5
1,Thailand,2023.5,1350.0,0.917431,0.0,0.912088,0.0,0.815217,0.0,1.000000,...,0,0,0,0,1,0,0,0,0,2023.5
2,Brazil,2023.0,1100.0,0.844037,0.0,0.912088,0.0,0.728261,0.0,1.000000,...,0,0,0,1,0,0,0,0,0,2023.0
3,Thailand,2019.5,1443.0,1.000000,0.0,0.912088,0.0,0.815217,0.0,0.440000,...,0,0,0,0,0,0,0,1,0,2019.5
4,Thailand,2023.5,1445.0,0.770642,0.0,1.000000,0.0,0.815217,0.0,0.666667,...,0,0,0,0,0,0,0,1,0,2023.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Vietnam,2023.5,670.0,0.311927,0.0,0.175824,0.0,0.184783,0.0,0.106667,...,0,0,1,0,0,0,0,0,0,2023.5
145,Thailand,2023.5,1320.0,0.082569,0.0,0.087912,0.0,0.000000,0.0,0.333333,...,0,0,0,0,1,0,0,0,0,2023.5
146,Thailand,2023.5,1100.0,0.229358,0.0,0.274725,0.0,0.184783,0.0,0.106667,...,0,0,0,0,0,0,0,1,0,2023.5
147,Thailand,2023.5,1400.0,0.082569,0.0,0.274725,0.0,0.184783,0.0,0.000000,...,0,0,0,0,0,0,0,1,0,2023.5
148,Ethiopia,2023.0,2000.0,0.229358,0.0,0.274725,0.0,0.271739,0.0,0.213333,...,0,0,0,0,0,0,0,1,0,2023.0

In [ ]:
df_2024.to_csv("coffee_data.csv", index=False)